vich_uploader:
    db_driver: orm
    storage: flysystem
    mappings:
        products:
            uri_prefix: /uploads/products
            upload_destination: '%kernel.project_dir%/public/uploads/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        merchants:
            uri_prefix: /uploads/merchants
            upload_destination: '%kernel.project_dir%/public/uploads/merchants'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
